default_platform(:android)

platform :android do
   desc "Assemble source"
    lane :assemble do
      gradle(task: "assembleRelease")
    end
    lane :assembleDev do
      gradle(task: "assembleDevRelease")
    end
end
