name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  github-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v3.0.0
        with:
          java-version: 17.0.2+8
          distribution: temurin
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew app:assembleMasterRelease
        env:
          KOTLIN_CICD_KEYSTORE_ALIAS: ${{ secrets.KOTLIN_CICD_KEYSTORE_ALIAS }}
          KOTLIN_CICD_KEYSTORE_PASSWORD: ${{ secrets.KOTLIN_CICD_KEYSTORE_PASSWORD }}
      - name: Make testfairy executable
        run: chmod +x ./testfairy-uploader.sh
      - name: Moving APK to TestFairy
        run: ./testfairy-uploader.sh app/build/outputs/apk/release/app-release.apk ${{ secrets.TESTFAIRY_API_KEY }}

  fastlane:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - run: ls
      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x
      - name: Install Dependencies
        run: gem install bundler && bundle install
      - name: Make gradlew executable
        run: chmod +x /home/runner/work/demo/demo/gradlew
      - name: Run Fastlane Assemble Lane
        run: fastlane assemble
      - name: Make testfairy executable
        run: chmod +x ./testfairy-uploader.sh
      - name: Moving APK to TestFairy
        run: ./testfairy-uploader.sh app/build/outputs/apk/release/app-release.apk ${{ secrets.TESTFAIRY_API_KEY }}
