name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  github-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v3.0.0
        with:
          java-version: 17.0.2+8
          distribution: temurin
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Upload APK
        uses: actions/upload-artifact@v3.0.0
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk
      - name: Make testfairy executable
        run: chmod +x ./testfairy-uploader.sh
      - name: Moving build to artifacts directory
        run: ./testfairy-uploader.sh app/build/outputs/apk/debug/app-debug.apk

  fastnale:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x
      - name: Install Dependencies
        run: gem install bundler && bundle install
      - name: Make gradlew executable
        run: chmod +x /home/runner/work/demo/demo/gradlew
      - name: Run Fastlane Assemble Lane
        run: fastlane assemble
      - name: Make testfairy executable
        run: chmod +x ./testfairy-uploader.sh
      - name: Moving build to artifacts directory
        run: ./testfairy-uploader.sh app/build/outputs/apk/debug/app-debug.apk
